// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {web_scraping} from '../models';

export function WebScrapingHorses(arg1:string):Promise<Array<web_scraping.Horse>>;
